let
    Source = Sql.Database("hw-crsrpt", "crs_interface", [Query="SELECT  #(lf)    d.Cnsmr_Accnt_Idntfr_Agncy_ID AS 'Accnt#',#(lf)    Desk,#(lf)    cat2.tag_shrt_nm AS 'I-tag',#(lf)    d.State AS 'State',               #(lf)    d.Status_Code AS 'Status Code',   #(lf)    d.Last_Status_Date AS 'Date Desk Assigned',  #(lf)    cat2.cnsmr_accnt_tag_assgn_dt AS 'tag_date',  #(lf)    CASE #(lf)        WHEN csreview.tag_shrt_nm IS NULL THEN 0 #(lf)        ELSE 1 #(lf)    END AS 'CSReview',  -- Added CSReview column with condition#(lf)    csreview.cnsmr_accnt_tag_assgn_dt AS 'CSReview_tag_date',  -- Added CSReview tag date#(lf)    CASE #(lf)        WHEN ramailhd.tag_shrt_nm IS NULL THEN 0 #(lf)        ELSE 1 #(lf)    END AS 'RAMailHd',  -- Added RAMailHd column with condition#(lf)    ramailhd.cnsmr_accnt_tag_assgn_dt AS 'RAMailHd_Date_Assigned',  -- Added RAMailHd Date Assigned column#(lf)    CASE#(lf)        WHEN raholdtag.tag_shrt_nm IS NULL THEN 0 #(lf)        ELSE 1 #(lf)    END AS 'RAHold_Tag',  -- Added RA-HOLD column with condition#(lf)    c.SSN AS 'SSN'  -- Added SSN column from Consumer table#(lf)FROM  #(lf)    [CRS_Interface].[dbo].[Cnsmr_Accnt_Service] cas (NOLOCK)#(lf)    --join CRS_Interface.dbo.vw_cnsmr c (NOLOCK) on c.Cnsmr_Accnt_ID = cas.Cnsmr_Accnt_ID#(lf)    JOIN CRS_Interface.dbo.vw_debtor d (NOLOCK) on d.Cnsmr_Accnt_ID = cas.Cnsmr_Accnt_ID#(lf)    JOIN CRS_Interface.dbo.vw_Client cl (NOLOCK) on cl.Client_Number = d.Client_Number#(lf)    OUTER APPLY (#(lf)        SELECT TOP 1 #(lf)            cat2.cnsmr_accnt_id,#(lf)            t.tag_shrt_nm,#(lf)            cat2.cnsmr_accnt_tag_assgn_dt  #(lf)        FROM #(lf)            crs5_oltp_replicated.dbo.cnsmr_Accnt_Tag cat2 (NOLOCK)#(lf)        JOIN #(lf)            crs_interface.dbo.vw_tags t (NOLOCK) on t.tag_id = cat2.tag_id #(lf)        WHERE #(lf)            cat2.cnsmr_accnt_id = d.Cnsmr_Accnt_ID#(lf)            AND t.tag_shrt_nm LIKE 'I-%'#(lf)        --and cat2.tag_id in (1636,1638,1637,1639,1640,1641) #(lf)        --and cat2.cnsmr_accnt_sft_delete_flg = 'N'#(lf)    ) Cat2#(lf) #(lf)    OUTER APPLY (#(lf)        SELECT TOP 1 #(lf)            tag.tag_shrt_nm, #(lf)            cat3.cnsmr_accnt_tag_assgn_dt#(lf)        FROM #(lf)            crs5_oltp_replicated.dbo.cnsmr_Accnt_Tag cat3 (NOLOCK)#(lf)        JOIN #(lf)            crs5_oltp_replicated.dbo.tag tag (NOLOCK) on tag.tag_id = cat3.tag_id#(lf)        WHERE #(lf)            cat3.cnsmr_accnt_id = d.Cnsmr_Accnt_ID#(lf)            AND tag.tag_shrt_nm = 'CSReview'  -- Filtering for CSReview tag#(lf)    ) csreview  -- Added CSReview lookup#(lf) #(lf)    OUTER APPLY (#(lf)        SELECT TOP 1 #(lf)            tag.tag_shrt_nm,#(lf)            cat4.cnsmr_accnt_tag_assgn_dt#(lf)        FROM #(lf)            crs5_oltp_replicated.dbo.cnsmr_Accnt_Tag cat4 (NOLOCK)#(lf)        JOIN #(lf)            crs5_oltp_replicated.dbo.tag tag (NOLOCK) on tag.tag_id = cat4.tag_id#(lf)        WHERE #(lf)            cat4.cnsmr_accnt_id = d.Cnsmr_Accnt_ID#(lf)            AND tag.tag_shrt_nm = 'RAMailHd'  -- Filtering for RAMailHd tag#(lf)    ) ramailhd  -- Added RAMailHd lookup#(lf) #(lf)    OUTER APPLY (#(lf)        SELECT TOP 1 #(lf)            tag.tag_shrt_nm,#(lf)            cat5.cnsmr_accnt_tag_assgn_dt#(lf)        FROM #(lf)            crs5_oltp_replicated.dbo.cnsmr_Accnt_Tag cat5 (NOLOCK)#(lf)        JOIN #(lf)            crs5_oltp_replicated.dbo.tag tag (NOLOCK) on tag.tag_id = cat5.tag_id#(lf)        WHERE #(lf)            cat5.cnsmr_accnt_id = d.Cnsmr_Accnt_ID#(lf)            AND tag.tag_shrt_nm = 'RA-HOLD'  -- Filtering for RA-HOLD tag#(lf)    ) raholdtag -- Added RA-HOLD lookup#(lf) #(lf)    LEFT JOIN CRS_Interface.dbo.Consumer c (NOLOCK) ON c.Cnsmr_Accnt_ID = d.Cnsmr_Accnt_ID  -- Join for SSN column#(lf)#(lf)Where #(lf)    --Desk like 'RA%'#(lf)    Desk in ('RACease','ResAdvct','RASpec','RAShrdSv','RAHS1','RAHS2','RAHS3','RAHS4','RAHS5','RAFL1','RAFL2','RAFL3','RAFL4','RAFL5','RAFL6','RAFL7');#(lf)"]),
    #"Duplicated Column" = Table.DuplicateColumn(Source, "Date Desk Assigned", "Date Desk Assigned - Copy"),
    #"Changed Type" = Table.TransformColumnTypes(#"Duplicated Column",{{"Date Desk Assigned - Copy", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Date Desk Assigned - Copy", "Assigned Date"}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns", "tag_date", "tag_date - Copy"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"tag_date - Copy", "Assigned Tag Date"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Assigned Tag Date", type date}}),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Changed Type1", "CSReview_tag_date", "CSReview_tag_date - Copy"),
    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column2",{"Accnt#", "Desk", "I-tag", "State", "Status Code", "Date Desk Assigned", "tag_date", "CSReview", "CSReview_tag_date", "CSReview_tag_date - Copy", "RAMailHd", "RAMailHd_Date_Assigned", "Assigned Date", "Assigned Tag Date"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns",{{"CSReview_tag_date - Copy", "CSReview_Date"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns2",{{"CSReview_Date", type date}}),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Changed Type2", "RAMailHd_Date_Assigned", "RAMailHd_Date_Assigned - Copy"),
    #"Reordered Columns1" = Table.ReorderColumns(#"Duplicated Column3",{"Accnt#", "Desk", "I-tag", "State", "Status Code", "Date Desk Assigned", "tag_date", "CSReview", "CSReview_tag_date", "CSReview_Date", "RAMailHd", "RAMailHd_Date_Assigned", "RAMailHd_Date_Assigned - Copy", "Assigned Date", "Assigned Tag Date"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns1",{{"RAMailHd_Date_Assigned - Copy", "RAMailHd_Date"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"RAMailHd_Date", type date}})
in
    #"Changed Type3"