Total_Revenue_Risks = COUNTROWS(FILTER(Balance_Adjustment, Balance_Adjustment[PND1_Status_Label] = "Not Sent" || Balance_Adjustment[BOC_Status_Label] = "Not Sent" && Balance_Adjustment[Comm_Aft_Adj] = "No" || Balance_Adjustment[SSN/DOB ] = 0))